# Generated by Django 3.1.5 on 2021-01-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210116_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('blogid', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_likes',
        ),
    ]
