# Generated by Django 3.1.5 on 2021-01-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210127_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='userid',
            field=models.CharField(max_length=50),
        ),
    ]
