# Generated by Django 3.1.5 on 2021-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210127_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('OTP', models.CharField(max_length=50)),
            ],
        ),
    ]
