# Generated by Django 3.1.5 on 2021-01-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_comment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
