# Generated by Django 3.1.5 on 2021-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
            ],
        ),
    ]
