# Generated by Django 3.1.5 on 2021-01-31 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comreply', models.CharField(max_length=500)),
                ('commentid', models.CharField(max_length=50)),
                ('comonuserid', models.CharField(max_length=50)),
                ('comdate', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
